Remove --preserve option from Talos upgrade commands for all nodes

diff --git a/.github/workflows/update-talos-machines.yaml b/.github/workflows/update-talos-machines.yaml
--- a/.github/workflows/update-talos-machines.yaml
+++ b/.github/workflows/update-talos-machines.yaml
@@ -80,7 +80,7 @@ jobs:
         run: |
           talosctl version -n $WILLIAM
           echo "Updating william ($WILLIAM) to $IMAGE"
-          talosctl upgrade --nodes $WILLIAM --image $IMAGE --preserve --wait || echo "Failed to update william"
+          talosctl upgrade --nodes $WILLIAM --image $IMAGE --wait || echo "Failed to update william"
           sleep 30
 
       - name: Update Talos node manta
@@ -89,8 +89,9 @@ jobs:
           IMAGE: factory.talos.dev/installer/${{ steps.schematic.outputs.id }}:${{ steps.talos-version.outputs.version }}
           TALOSCONFIG: ~/.talos/config
         run: |
+          talosctl version -n $MANTA
           echo "Updating manta ($MANTA) to $IMAGE"
-          talosctl upgrade --nodes $MANTA --image $IMAGE --preserve --wait || echo "Failed to update manta"
+          talosctl upgrade --nodes $MANTA --image $IMAGE --wait || echo "Failed to update manta"
           sleep 30
 
       - name: Update Talos node skidbladnir
@@ -99,8 +100,9 @@ jobs:
           IMAGE: factory.talos.dev/installer/${{ steps.schematic.outputs.id }}:${{ steps.talos-version.outputs.version }}
           TALOSCONFIG: ~/.talos/config
         run: |
+          talosctl version -n $SKIDBLADNIR
           echo "Updating skidbladnir ($SKIDBLADNIR) to $IMAGE"
-          talosctl upgrade --nodes $SKIDBLADNIR --image $IMAGE --preserve --wait || echo "Failed to update skidbladnir"
+          talosctl upgrade --nodes $SKIDBLADNIR --image $IMAGE --wait || echo "Failed to update skidbladnir"
           sleep 30
 
       - name: Update Talos node yumi
@@ -109,8 +111,9 @@ jobs:
           IMAGE: factory.talos.dev/installer/${{ steps.schematic.outputs.id }}:${{ steps.talos-version.outputs.version }}
           TALOSCONFIG: ~/.talos/config
         run: |
+          talosctl version -n $YUMI
           echo "Updating yumi ($YUMI) to $IMAGE"
-          talosctl upgrade --nodes $YUMI --image $IMAGE --preserve --wait || echo "Failed to update yumi"
+          talosctl upgrade --nodes $YUMI --image $IMAGE --wait || echo "Failed to update yumi"
 
       - name: Summary
         run: |
